---
galaxy_info:
  author: Vlad Ghinea and Bert Van Vreckem
  description: This role installs and configures Samba as a file server.
  license: BSD
  min_ansible_version: '2.11'
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - buster
    - name: Fedora
      versions:
        - '37'
        - '38'
    - name: EL
      versions:
        - '8'
        - '9'
    - name: ArchLinux
      versions:
        - all
  galaxy_tags:
    - system
    - networking
dependencies: []
